package org.unfpa.otg.knowledge

import android.content.Context
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.unfpa.otg.db.AppDatabase
import org.unfpa.otg.db.FormularyEntry

/**
 * FormularyRepository — loads formulary.json from assets and exposes
 * structured drug lookup with localisation support.
 *
 * Drug doses are NEVER generated by the LLM. They come exclusively from
 * this repository. The LLM emits <<DOSE_CARD_REQUEST:drug_name>> triggers;
 * the UI renders a DoseCard fetched from here.
 */
class FormularyRepository(private val context: Context) {

    private val db = AppDatabase.getInstance(context)
    private val json = Json { ignoreUnknownKeys = true }

    @Serializable
    data class FormularyJsonEntry(
        val drug: String,
        val genericName: String,
        val localNames: Map<String, String> = emptyMap(),
        val indication: String,
        val dose: String,
        val route: String,
        val timing: String,
        val alternativeDose: String? = null,
        val contraindications: List<String> = emptyList(),
        val warnings: List<String> = emptyList(),
        val source: String,
        val sourceChunkId: String,
        val sourceUrl: String,
        val whoEmlListed: Boolean = false,
        val `_clinicalStatus`: String = "UNVERIFIED-SCAFFOLD",
        val reviewedBy: String? = null,
        val reviewedAt: String? = null,
        val expiryDate: String? = null,
    )

    @Serializable
    data class FormularyFile(
        val drugs: List<FormularyJsonEntry>,
    )

    data class DrugCard(
        val drug: String,
        val displayName: String,              // localised if available, else genericName
        val indication: String,
        val dose: String,
        val route: String,
        val timing: String,
        val alternativeDose: String?,
        val contraindications: List<String>,
        val warnings: List<String>,
        val source: String,
        val sourceChunkId: String,
        val sourceUrl: String,
        val whoEmlListed: Boolean,
        val clinicalStatus: String,
        val isExpired: Boolean,
    )

    suspend fun initialise() = withContext(Dispatchers.IO) {
        if (db.formularyDao().count() > 0) return@withContext
        loadFormularyFromAssets()
    }

    private suspend fun loadFormularyFromAssets() {
        val raw = context.assets.open("formulary/formulary.json")
            .bufferedReader().readText()

        // The formulary.json has a top-level object with a "drugs" array
        // and a "_meta" object — parse with a forgiving approach
        val jsonObj = json.parseToJsonElement(raw) as? kotlinx.serialization.json.JsonObject
        val drugsArray = jsonObj?.get("drugs") as? kotlinx.serialization.json.JsonArray
            ?: return

        val entries = drugsArray.mapNotNull { element ->
            try {
                val entry = json.decodeFromJsonElement(FormularyJsonEntry.serializer(), element)
                FormularyEntry(
                    drug = entry.drug,
                    genericName = entry.genericName,
                    localNamesJson = json.encodeToString(
                        kotlinx.serialization.builtins.MapSerializer(
                            kotlinx.serialization.builtins.serializer(),
                            kotlinx.serialization.builtins.serializer()
                        ),
                        entry.localNames
                    ),
                    indication = entry.indication,
                    dose = entry.dose,
                    route = entry.route,
                    timing = entry.timing,
                    alternativeDose = entry.alternativeDose,
                    contraindicationsJson = json.encodeToString(
                        kotlinx.serialization.builtins.ListSerializer(
                            kotlinx.serialization.builtins.serializer()
                        ),
                        entry.contraindications
                    ),
                    warningsJson = json.encodeToString(
                        kotlinx.serialization.builtins.ListSerializer(
                            kotlinx.serialization.builtins.serializer()
                        ),
                        entry.warnings
                    ),
                    source = entry.source,
                    sourceChunkId = entry.sourceChunkId,
                    sourceUrl = entry.sourceUrl,
                    whoEmlListed = entry.whoEmlListed,
                    clinicalStatus = entry.`_clinicalStatus`,
                    reviewedBy = entry.reviewedBy,
                    reviewedAt = entry.reviewedAt,
                    expiryDate = entry.expiryDate,
                )
            } catch (e: Exception) { null }
        }
        db.formularyDao().upsertAll(entries)
    }

    /**
     * Look up a drug by name (case-insensitive, partial match).
     * Returns a localised DrugCard for the given BCP-47 language code.
     */
    suspend fun getDrugCard(drugQuery: String, language: String = "en"): DrugCard? =
        withContext(Dispatchers.IO) {
            val normalised = drugQuery.lowercase().trim()
            val entry = db.formularyDao().getAll().firstOrNull { e ->
                e.drug == normalised ||
                e.genericName.lowercase() == normalised ||
                e.drug.contains(normalised) ||
                e.genericName.lowercase().contains(normalised)
            } ?: return@withContext null

            val localNames = try {
                json.decodeFromString<Map<String, String>>(entry.localNamesJson)
            } catch (e: Exception) { emptyMap() }

            val displayName = localNames[language]
                ?: localNames[language.substringBefore("-")]
                ?: entry.genericName

            val contraindications = try {
                json.decodeFromString<List<String>>(entry.contraindicationsJson)
            } catch (e: Exception) { emptyList() }

            val warnings = try {
                json.decodeFromString<List<String>>(entry.warningsJson)
            } catch (e: Exception) { emptyList() }

            val isExpired = entry.expiryDate?.let { expiry ->
                try {
                    val parts = expiry.split("-")
                    val expiryYear = parts[0].toInt()
                    val expiryMonth = parts[1].toInt()
                    val now = java.util.Calendar.getInstance()
                    val nowYear = now.get(java.util.Calendar.YEAR)
                    val nowMonth = now.get(java.util.Calendar.MONTH) + 1
                    expiryYear < nowYear || (expiryYear == nowYear && expiryMonth < nowMonth)
                } catch (e: Exception) { false }
            } ?: false

            DrugCard(
                drug = entry.drug,
                displayName = displayName,
                indication = entry.indication,
                dose = entry.dose,
                route = entry.route,
                timing = entry.timing,
                alternativeDose = entry.alternativeDose,
                contraindications = contraindications,
                warnings = warnings,
                source = entry.source,
                sourceChunkId = entry.sourceChunkId,
                sourceUrl = entry.sourceUrl,
                whoEmlListed = entry.whoEmlListed,
                clinicalStatus = entry.clinicalStatus,
                isExpired = isExpired,
            )
        }

    suspend fun getAllDrugs(): List<FormularyEntry> = withContext(Dispatchers.IO) {
        db.formularyDao().getAll()
    }
}
