package org.unfpa.otg.knowledge

import android.content.Context
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import org.unfpa.otg.db.AppDatabase
import org.unfpa.otg.db.KnowledgeChunk
import org.unfpa.otg.db.KnowledgeDoc

/**
 * KnowledgeRepository — loads knowledge/index.json from assets on first use,
 * populates Room, and delegates vector search to VectorSearch.
 *
 * index.json is generated by scripts/precompute-android-assets.ts and contains
 * all chunk text, citation metadata, and a parallel vectors.bin binary file for
 * pre-computed embeddings.
 */
class KnowledgeRepository(
    private val context: Context,
    private val embeddingEngine: EmbeddingEngine,
    private val vectorSearch: VectorSearch,
) {
    private val db = AppDatabase.getInstance(context)
    private val json = Json { ignoreUnknownKeys = true }

    @Serializable
    data class IndexChunk(
        val chunkId: String,
        val docSlug: String,
        val chunkIndex: Int,
        val content: String,
        val contentHash: String,
        val documentTitle: String,
        val vertical: String,
        val sourceDocument: String = "",
        val sourceEdition: String = "",
        val sourceSection: String = "",
        val sourcePage: Int = 0,
        val sourceUrl: String = "",
        val verbatimExcerpt: String = "",
        val expiryDate: String? = null,
        val language: String = "en",
    )

    @Serializable
    data class IndexFile(
        val version: String,
        val generatedAt: String,
        val chunkCount: Int,
        val chunks: List<IndexChunk>,
    )

    data class SearchResult(
        val chunkId: String,
        val documentTitle: String,
        val docSlug: String,
        val content: String,
        val sourcePage: Int,
        val sourceSection: String,
        val sourceDocument: String,
        val sourceUrl: String,
        val verbatimExcerpt: String,
        val expiryDate: String?,
        val score: Float,
    )

    private var initialised = false

    suspend fun initialise() = withContext(Dispatchers.IO) {
        if (initialised) return@withContext
        if (db.knowledgeChunkDao().count() == 0) {
            loadAssetsIntoDb()
        }
        vectorSearch.load(db.knowledgeChunkDao().getAll())
        initialised = true
    }

    private suspend fun loadAssetsIntoDb() {
        val indexJson = context.assets.open("knowledge/index.json")
            .bufferedReader().readText()
        val index = json.decodeFromString<IndexFile>(indexJson)

        val docs = mutableMapOf<String, KnowledgeDoc>()
        val chunks = mutableListOf<KnowledgeChunk>()

        // Load embedding vectors from binary file (Float32LE, 384 dims per chunk)
        val vectorsBytes = context.assets.open("embeddings/vectors.bin").readBytes()
        val floatBuf = java.nio.ByteBuffer.wrap(vectorsBytes)
            .order(java.nio.ByteOrder.LITTLE_ENDIAN)
            .asFloatBuffer()

        index.chunks.forEachIndexed { i, c ->
            docs.getOrPut(c.docSlug) {
                KnowledgeDoc(
                    slug = c.docSlug,
                    title = c.documentTitle,
                    vertical = c.vertical,
                    contentHash = c.contentHash,
                    expiryDate = c.expiryDate,
                    sourceUrl = c.sourceUrl.ifBlank { null },
                    language = c.language,
                    ingestedAt = System.currentTimeMillis(),
                )
            }

            val embeddingBytes = ByteArray(384 * 4)
            val floatSlice = FloatArray(384)
            floatBuf.position(i * 384)
            floatBuf.get(floatSlice, 0, 384)
            java.nio.ByteBuffer.wrap(embeddingBytes)
                .order(java.nio.ByteOrder.LITTLE_ENDIAN)
                .asFloatBuffer()
                .put(floatSlice)

            chunks.add(KnowledgeChunk(
                chunkId = c.chunkId,
                docSlug = c.docSlug,
                chunkIndex = c.chunkIndex,
                content = c.content,
                contentHash = c.contentHash,
                embedding = embeddingBytes,
                sourceDocument = c.sourceDocument,
                sourceEdition = c.sourceEdition,
                sourceSection = c.sourceSection,
                sourcePage = c.sourcePage,
                sourceUrl = c.sourceUrl,
                verbatimExcerpt = c.verbatimExcerpt,
                expiryDate = c.expiryDate,
                language = c.language,
                ingestedAt = System.currentTimeMillis(),
            ))
        }

        db.knowledgeDocDao().upsertAll(docs.values.toList())
        db.knowledgeChunkDao().upsertAll(chunks)
    }

    suspend fun search(
        query: String,
        topK: Int = 5,
        verticals: List<String> = emptyList(),
    ): List<SearchResult> = withContext(Dispatchers.Default) {
        val queryEmbedding = embeddingEngine.embed(query)
        val rawResults = vectorSearch.search(queryEmbedding, topK * 3) // over-fetch, then filter

        val filtered = if (verticals.isEmpty()) rawResults else {
            rawResults.filter { r ->
                verticals.any { v ->
                    // MOH_MMR matches "MOH_MMR" vertical, or "MOH" prefix wildcard
                    r.vertical == v || (v.startsWith("MOH_") && r.vertical == v)
                }
            }
        }

        filtered.take(topK).map { r ->
            SearchResult(
                chunkId = r.chunkId,
                documentTitle = r.documentTitle,
                docSlug = r.docSlug,
                content = r.content,
                sourcePage = r.sourcePage,
                sourceSection = r.sourceSection,
                sourceDocument = r.sourceDocument,
                sourceUrl = r.sourceUrl,
                verbatimExcerpt = r.verbatimExcerpt,
                expiryDate = r.expiryDate,
                score = r.score,
            )
        }
    }

    suspend fun chunkExists(chunkId: String): Boolean = withContext(Dispatchers.IO) {
        db.knowledgeChunkDao().getById(chunkId) != null
    }

    suspend fun getChunk(chunkId: String): KnowledgeChunk? = withContext(Dispatchers.IO) {
        db.knowledgeChunkDao().getById(chunkId)
    }
}
